version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - app-net

  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - app-net

  tests:
    image: maven:3.9.9-eclipse-temurin-21
    volumes:
      - ./selenium-tests:/app        # ← mounts selenium-tests folder into container
    working_dir: /app
    depends_on:
      - selenium-hub
      - chrome
    networks:
      - app-net
    command: >
      sh -c "
      echo 'Waiting for Selenium Grid...';
      until curl -s http://selenium-hub:4444/wd/hub/status | grep -q '\"ready\":true'; do
        sleep 2;
      done;
      echo 'Grid is ready. Running tests...';
      mvn clean test
      "

networks:
  app-net:
    external: true